name: Blog deployer

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build and publish by GitHub Actions
    runs-on: ubuntu-latest
    env:
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
      BAIDU_URL_SUBMIT_TOKEN: ${{ secrets.BAIDU_URL_SUBMIT_TOKEN }}
    steps:
    - name: 1. Git Checkout
      uses: actions/checkout@master
      
    - name: 2. Install Nodejs 10.x
      uses: actions/setup-node@v1
    
    - name: 3. Install Hexo
      run: |
        npm install hexo-cli -g
        npm install
        
    - name: 4. Generate Public Files
      run: |
        hexo clean
        hexo g
        hexo d
        hexo algolia

    - name: 5. Deploy To Github Pages...
      env:
        GH_REF: github.com/iBestRead/iBestRead.github.io.git
      run: |
        git config --global user.name "akinix"
        git config --global user.email "akinixu@gmail.com"
        git log --pretty=format:"CI: %s" --date=short -n 1  > commit-message.log
        git clone https://${GH_REF} .deploy_github
        cd .deploy_github
        git checkout master
        cd ../
        mv .deploy_github/.git/ ./public/
        cd ./public/
        git add .
        git commit -F ../commit-message.log
        git push --force --quiet "https://${{ secrets.GH_TOKEN }}@${GH_REF}" master:master

    - name: 6. Remove public .git
      run: rm -rf *
      working-directory: ./public/.git
        
    - name: 6. Deploy To Coding...
      env:
        CODING_REF: e.coding.net/ibestread/Blog.git
      run: |
        git config --global user.name "akinix"
        git config --global user.email "akinix@qq.com"
        git log --pretty=format:"CI: %s" --date=short -n 1  > commit-message.log
        git clone https://${CODING_REF} .deploy_coding
        cd .deploy_coding
        git checkout master
        cd ../
        mv .deploy_git/.git/ ./public/
        cd ./public/
        git add .
        git commit -F ../commit-message.log
        git push --force --quiet "https://${{ secrets.CODING_USERNAME }}:${{ secrets.CODING_TOKEN }}@${CODING_REF}" master:master